export type Product = {
  name: string;
  color: string;
  price: number;
  gender: "male" | "female";
  type: "hoodie" | "polo" | "basic";
  img: string;
};

export const PRODUCTS: Product[] = [
  {
    name: "Black Hoodie",
    color: "black",
    type: "hoodie",
    price: 450,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "Pink Polo",
    color: "pink",
    type: "polo",
    price: 230,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "Blue Basic Tee",
    color: "blue",
    type: "basic",
    price: 300,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "Green Hoodie",
    color: "green",
    type: "hoodie",
    price: 500,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "Red Basic Tee",
    color: "red",
    type: "basic",
    price: 250,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "Black Polo",
    color: "black",
    type: "polo",
    price: 320,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "Pink Hoodie",
    color: "pink",
    type: "hoodie",
    price: 380,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "Green Basic Tee",
    color: "green",
    type: "basic",
    price: 220,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "Blue Polo",
    color: "blue",
    type: "polo",
    price: 260,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "Red Hoodie",
    color: "red",
    type: "hoodie",
    price: 400,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "Black Basic Tee",
    color: "black",
    type: "basic",
    price: 210,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "Pink Basic Tee",
    color: "pink",
    type: "basic",
    price: 270,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "Blue Hoodie",
    color: "blue",
    type: "hoodie",
    price: 480,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "Green Polo",
    color: "green",
    type: "polo",
    price: 310,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "Red Basic Tee",
    color: "red",
    type: "basic",
    price: 240,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "Black Hoodie",
    color: "black",
    type: "hoodie",
    price: 390,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "Pink Polo",
    color: "pink",
    type: "polo",
    price: 210,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "Blue Basic Tee",
    color: "blue",
    type: "basic",
    price: 260,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "Green Hoodie",
    color: "green",
    type: "hoodie",
    price: 520,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "Red Polo",
    color: "red",
    type: "polo",
    price: 290,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "Black Basic Tee",
    color: "black",
    type: "basic",
    price: 280,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "Pink Hoodie",
    color: "pink",
    type: "hoodie",
    price: 370,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "Blue Polo",
    color: "blue",
    type: "polo",
    price: 250,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "Green Basic Tee",
    color: "green",
    type: "basic",
    price: 290,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "Red Hoodie",
    color: "red",
    type: "hoodie",
    price: 450,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "Black Polo",
    color: "black",
    type: "polo",
    price: 230,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "Pink Basic Tee",
    color: "pink",
    type: "basic",
    price: 300,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "Blue Hoodie",
    color: "blue",
    type: "hoodie",
    price: 420,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "Green Polo",
    color: "green",
    type: "polo",
    price: 270,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "Red Basic Tee",
    color: "red",
    type: "basic",
    price: 310,
    gender: "female",
    img: "products/green.svg",
  },
];
