export type Product = {
  id: string;
  name: string;
  color: string;
  price: number;
  gender: "male" | "female";
  type: "hoodie" | "polo" | "basic";
  img: string;
};

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "black hoodie",
    color: "black",
    type: "hoodie",
    price: 450,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    id: "2",
    name: "pink polo",
    color: "pink",
    type: "polo",
    price: 230,
    gender: "female",
    img: "products/red.svg",
  },
  {
    id: "3",
    name: "blue basic tee",
    color: "blue",
    type: "basic",
    price: 300,
    gender: "male",
    img: "products/green.svg",
  },
  {
    id: "4",
    name: "green hoodie",
    color: "green",
    type: "hoodie",
    price: 500,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    id: "5",
    name: "red basic tee",
    color: "red",
    type: "basic",
    price: 250,
    gender: "male",
    img: "products/red.svg",
  },
  {
    id: "6",
    name: "black polo",
    color: "black",
    type: "polo",
    price: 320,
    gender: "female",
    img: "products/green.svg",
  },
  {
    id: "7",
    name: "pink hoodie",
    color: "pink",
    type: "hoodie",
    price: 380,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    id: "8",
    name: "green basic tee",
    color: "green",
    type: "basic",
    price: 220,
    gender: "female",
    img: "products/red.svg",
  },
  {
    id: "9",
    name: "blue polo",
    color: "blue",
    type: "polo",
    price: 260,
    gender: "male",
    img: "products/green.svg",
  },
  {
    id: "10",
    name: "red hoodie",
    color: "red",
    type: "hoodie",
    price: 400,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    id: "11",
    name: "black basic tee",
    color: "black",
    type: "basic",
    price: 210,
    gender: "male",
    img: "products/red.svg",
  },
  {
    id: "12",
    name: "pink basic tee",
    color: "pink",
    type: "basic",
    price: 270,
    gender: "female",
    img: "products/green.svg",
  },
  {
    id: "13",
    name: "blue hoodie",
    color: "blue",
    type: "hoodie",
    price: 480,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    id: "14",
    name: "green polo",
    color: "green",
    type: "polo",
    price: 310,
    gender: "female",
    img: "products/red.svg",
  },
  {
    id: "15",
    name: "red basic tee",
    color: "red",
    type: "basic",
    price: 240,
    gender: "male",
    img: "products/green.svg",
  },
  {
    id: "16",
    name: "black hoodie",
    color: "black",
    type: "hoodie",
    price: 390,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    id: "17",
    name: "pink polo",
    color: "pink",
    type: "polo",
    price: 210,
    gender: "male",
    img: "products/red.svg",
  },
  {
    id: "18",
    name: "blue basic tee",
    color: "blue",
    type: "basic",
    price: 260,
    gender: "female",
    img: "products/green.svg",
  },
  {
    id: "19",
    name: "green hoodie",
    color: "green",
    type: "hoodie",
    price: 520,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    id: "20",
    name: "red polo",
    color: "red",
    type: "polo",
    price: 290,
    gender: "female",
    img: "products/red.svg",
  },
  {
    id: "21",
    name: "black basic tee",
    color: "black",
    type: "basic",
    price: 280,
    gender: "male",
    img: "products/green.svg",
  },
  {
    id: "22",
    name: "pink hoodie",
    color: "pink",
    type: "hoodie",
    price: 370,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    id: "23",
    name: "blue polo",
    color: "blue",
    type: "polo",
    price: 250,
    gender: "male",
    img: "products/red.svg",
  },
  {
    id: "24",
    name: "green basic tee",
    color: "green",
    type: "basic",
    price: 290,
    gender: "female",
    img: "products/green.svg",
  },
  {
    id: "25",
    name: "red hoodie",
    color: "red",
    type: "hoodie",
    price: 450,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    id: "26",
    name: "black polo",
    color: "black",
    type: "polo",
    price: 230,
    gender: "female",
    img: "products/red.svg",
  },
  {
    id: "27",
    name: "pink basic tee",
    color: "pink",
    type: "basic",
    price: 300,
    gender: "male",
    img: "products/green.svg",
  },
  {
    id: "28",
    name: "blue hoodie",
    color: "blue",
    type: "hoodie",
    price: 420,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    id: "29",
    name: "green polo",
    color: "green",
    type: "polo",
    price: 270,
    gender: "male",
    img: "products/red.svg",
  },
  {
    id: "30",
    name: "red basic tee",
    color: "red",
    type: "basic",
    price: 310,
    gender: "female",
    img: "products/green.svg",
  },
];
