export type Product = {
  name: string;
  color: string;
  price: number;
  gender: "male" | "female";
  type: "hoodie" | "polo" | "basic";
  img: string;
};

export const PRODUCTS: Product[] = [
  {
    name: "black hoodie",
    color: "black",
    type: "hoodie",
    price: 450,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "pink polo",
    color: "pink",
    type: "polo",
    price: 230,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "blue basic tee",
    color: "blue",
    type: "basic",
    price: 300,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "green hoodie",
    color: "green",
    type: "hoodie",
    price: 500,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "red basic tee",
    color: "red",
    type: "basic",
    price: 250,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "black polo",
    color: "black",
    type: "polo",
    price: 320,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "pink hoodie",
    color: "pink",
    type: "hoodie",
    price: 380,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "green basic tee",
    color: "green",
    type: "basic",
    price: 220,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "blue polo",
    color: "blue",
    type: "polo",
    price: 260,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "red hoodie",
    color: "red",
    type: "hoodie",
    price: 400,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "black basic tee",
    color: "black",
    type: "basic",
    price: 210,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "pink basic tee",
    color: "pink",
    type: "basic",
    price: 270,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "blue hoodie",
    color: "blue",
    type: "hoodie",
    price: 480,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "green polo",
    color: "green",
    type: "polo",
    price: 310,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "red basic tee",
    color: "red",
    type: "basic",
    price: 240,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "black hoodie",
    color: "black",
    type: "hoodie",
    price: 390,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "pink polo",
    color: "pink",
    type: "polo",
    price: 210,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "blue basic tee",
    color: "blue",
    type: "basic",
    price: 260,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "green hoodie",
    color: "green",
    type: "hoodie",
    price: 520,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "red polo",
    color: "red",
    type: "polo",
    price: 290,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "black basic tee",
    color: "black",
    type: "basic",
    price: 280,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "pink hoodie",
    color: "pink",
    type: "hoodie",
    price: 370,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "blue polo",
    color: "blue",
    type: "polo",
    price: 250,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "green basic tee",
    color: "green",
    type: "basic",
    price: 290,
    gender: "female",
    img: "products/green.svg",
  },
  {
    name: "red hoodie",
    color: "red",
    type: "hoodie",
    price: 450,
    gender: "male",
    img: "products/blue.svg",
  },
  {
    name: "black polo",
    color: "black",
    type: "polo",
    price: 230,
    gender: "female",
    img: "products/red.svg",
  },
  {
    name: "pink basic tee",
    color: "pink",
    type: "basic",
    price: 300,
    gender: "male",
    img: "products/green.svg",
  },
  {
    name: "blue hoodie",
    color: "blue",
    type: "hoodie",
    price: 420,
    gender: "female",
    img: "products/blue.svg",
  },
  {
    name: "green polo",
    color: "green",
    type: "polo",
    price: 270,
    gender: "male",
    img: "products/red.svg",
  },
  {
    name: "red basic tee",
    color: "red",
    type: "basic",
    price: 310,
    gender: "female",
    img: "products/green.svg",
  },
];
